academy/academy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users.views import (
    RegisterFormView,
    AccountView,
    PaymentDelete,
    session_enrollment,
    PaymentUpdate
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='course/home.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('account/', AccountView.as_view(), name='account'),
    path('enrollment/create/', session_enrollment, name='session_enrollment'),
    path('enrollment/<int:pk>/delete/', PaymentDelete.as_view(), name='enrollment_delete'),
    path('enrollment/<int:pk>/edit/', PaymentUpdate.as_view(), name='payment_update'),
    path('', include('course.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academy/course/urls.py
from django.urls import path

from .views import (
    HomePageView,
    ResourceDetailView,
    DashboardView,
    FeedbackListView,
    FeedbackUserListView,
    FeedbackCreate,
    FeedbackUpdate,
    FeedbackDelete
)


urlpatterns = [
    path('', HomePageView.as_view(), name='course_home'),
    path('resource/', HomePageView.as_view(), name='resource'),
    path('resource/<int:pk>/', ResourceDetailView.as_view(), name='resource_detail'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/feedback/', FeedbackListView.as_view(), name='feedback'),
    path('dashboard/feedback/<str:username>', FeedbackUserListView.as_view(), name='user_feedback'),
    path('feedback/new/', FeedbackCreate.as_view(), name='feedback_create'),
    path('feedback/<int:pk>/edit/', FeedbackUpdate.as_view(), name='feedback_edit'),
    path('feedback/<int:pk>/delete/', FeedbackDelete.as_view(), name='feedback_delete'),
]

academy/course/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from PIL import Image


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    subject = models.CharField(max_length=240)
    content = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name_plural = "feedback"


class Instructor(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    image = models.ImageField(default='profile.jpg', upload_to='instructors')
    email = models.EmailField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        width, height = img.size
        if height < width:
            left = (width - height) / 2
            right = (width + height) / 2
            top = 0
            bottom = height
            img = img.crop((left, top, right, bottom))
        elif width < height:
            left = 0
            right = width
            top = 0
            bottom = width
            img = img.crop((left, top, right, bottom))
        if height > 500 and width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
        img.save(self.image.path)


class Resource(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=240, null=True, blank=True,
        help_text="Text shown on homepage under the name and image."
    )
    content = models.TextField(null=True, blank=True,
        help_text="Text shown on the individual resource page to describe the resource in depth."
    )
    image = models.ImageField(default='resource_default.jpg', upload_to='resources')
    order = models.SmallIntegerField(unique=True, null=True, blank=True,
        help_text="Order that the resource is displayed on the homepage. Must be unique."
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('resource_detail', kwargs={'pk':self.pk})

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 600 or img.width > 1000:
            output_size = (1000, 600)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Session(models.Model):
    name = models.CharField(max_length=240)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)    
    url = models.URLField(null=True, blank=True)
    capacity = models.SmallIntegerField(null=True, blank=True,
        help_text="If speicifed, the number will be shown along with the session title on the homepage and account page."
    )
    full = models.BooleanField(default=False,
        help_text="If checked, then then users can no longer register for the session and it will be greyed out on the homepage."
    )

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    author = models.CharField(max_length=100, null=True, blank=True)
    content = models.CharField(max_length=240)

    def __str__(self):
        return self.content

academy/course/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.views.generic.base import TemplateView

from users.models import Payment
from .models import Feedback, Instructor, Resource, Session, Testimonial
from users.forms import PaymentUpdateForm


class HomePageView(TemplateView):
    template_name = "course/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.datetime.today()
        context['sessions'] = Session.objects.all().filter(end_date__gte=today)
        context['resources'] = Resource.objects.all()
        context['testimonials'] = Testimonial.objects.all()
        context['instructors'] = Instructor.objects.all()
        return context


class ResourceDetailView(DetailView):
    model = Resource


class DashboardView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = "course/dashboard_overview.html"

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['users'] = User.objects.all().filter(is_staff=False).count()
        context['feedback'] = Feedback.objects.all().count()
        enrollments = Payment.objects.all()
        context['enrollments'] = enrollments.count()
        context['payments'] = enrollments.filter(paid=True).count()
        sessions = Session.objects.all()
        context['sessions'] = {}
        for session in sessions:
            context['sessions'][session.name] = {}
            session_enrollments = enrollments.filter(session=session.pk)
            if session_enrollments.count() > 0:
                context['sessions'][session.name] = {
                    'enrollments': [],
                    'paid': int(session_enrollments.filter(paid=True).count() / session_enrollments.count() * 100)
                }
                for enrollment in session_enrollments:
                    context['sessions'][session.name]['enrollments'].append({
                        'id': enrollment.pk,
                        'student': enrollment.user,
                        'payment': PaymentUpdateForm(instance=enrollment)
                    })
        return context

    def test_func(self):
        return self.request.user.is_superuser


class FeedbackListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Feedback
    ordering = ['-date_created']
    paginate_by = 5

    def test_func(self):
        return self.request.user.is_superuser


class FeedbackUserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'users/feedback_user.html'
    model = Feedback
    ordering = ['-date_created']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Feedback.objects.filter(user=user).order_by('-date_created')

    def test_func(self):
        return self.request.user.is_superuser


class FeedbackCreate(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['subject', 'content']
    success_url = '/account/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, f'Your feedback has been submitted.')
        return super().form_valid(form)


class FeedbackUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Feedback
    fields = ['subject', 'content']
    success_url = '/account/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        feedback = self.get_object()
        return feedback.user == self.request.user


class FeedbackDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Feedback
    success_url = '/account/'

    def test_func(self):
        feedback = self.get_object()
        return feedback.user == self.request.user

academy/course/templates/course/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>Academy</title>
        {% endif %}

        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />

        <!-- Font Awesome icons -->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>

        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />

        <!-- Bootstrap v4.5.3 & Grayscale v6.0.3 CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'course/css/grayscale.css' %}">
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'course/css/style.css' %}">
        {% block styles %}{% endblock styles %}
    </head>
    <body id="page-top">
        {% block header %}
            {% include 'course/includes/header.html' %}
        {% endblock header %}
        
        {% block messages %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endblock messages %}
        
        {% block content %} {% endblock content %}

        {% block footer %}
            {% include 'course/includes/footer.html' %}
        {% endblock footer %}
        <!-- Bootstrap core JS-->
        <script src="{% static 'course/js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'course/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Third party plugin JS-->
        <script src="{% static 'course/js/jquery-easing-1.4.1.min.js' %}"></script>
        <!-- Coustom JS-->
        {% block scripts %}
            <script src="{% static 'course/js/script.js' %}"></script>
        {% endblock scripts %}
    </body>
</html>

academy/course/templates/course/dashboard.html
{% extends "course/base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'course/css/sb-admin-2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'course/css/fontawesome-all.min.css' %}">
{% endblock styles %}
{% block header %}{% endblock header %}
{% block messages %}{% endblock messages %}
{% block content %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'course_home' %}">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-home"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Academy</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Dashboard
            </div>

            <!-- Nav Item - Overview -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Overview</span></a>
            </li>

            <!-- Nav Item - Feedback -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'feedback' %}">
                    <i class="fas fa-fw fa-comments"></i>
                    <span>Feedback</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Admin
            </div>

            <!-- Nav Item - Admin -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Overview</span></a>
            </li>

            <!-- Nav Item - Sessions -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:course_session_changelist' %}">
                    <i class="fas fa-fw fa-chalkboard"></i>
                    <span>Sessions</span></a>
            </li>

            <!-- Nav Item - Resources -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:course_resource_changelist' %}">
                    <i class="fas fa-fw fa-book"></i>
                    <span>Resources</span></a>
            </li>

            <!-- Nav Item - Testimonials -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:course_testimonial_changelist' %}">
                    <i class="fas fa-fw fa-quote-right"></i>
                    <span>Testimonials</span></a>
            </li>

            <!-- Nav Item - Instructors -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:course_instructor_changelist' %}">
                    <i class="fas fa-fw fa-chalkboard-teacher"></i>
                    <span>Instructors</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Users
            </div>

            <!-- Nav Item - Users -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:auth_user_changelist' %}">
                    <i class="fas fa-fw fa-user"></i>
                    <span>User List</span></a>
            </li>

            <!-- Nav Item - Payments -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:users_payment_changelist' %}">
                    <i class="fas fa-fw fa-dollar-sign"></i>
                    <span>Payments</span></a>
            </li>

            <!-- Sidebar Toggler -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-0 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account' %}" role="button">
                                <span class="mr-2 d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}

                <div class="container-fluid mt-4">
                    {% block dashboard %}{% endblock dashboard %}
                </div>
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Academy 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    {% block scripts %}
        <script src="{% static 'course/js/sb-admin-2.min.js' %}"></script>
    {% endblock scripts %}
{% endblock content %}
{% block footer %}{% endblock footer %}

academy/course/templates/course/dashboard_overview.html
{% extends "course/dashboard.html" %}
{% load crispy_forms_tags %}
{% block dashboard %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>
    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Students</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ users }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Total Enrollments
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ enrollments }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Payments
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ payments }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url 'feedback' %}">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                    Feedback
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ feedback }}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-comments fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Session Payments</h6>
                </div>
                <div class="card-body">
                    <div class="accordion" id="session-payments">
                        {% for session, val in sessions.items %}
                                <div class="card">
                                    <div class="card-header" id="heading{{ forloop.counter }}">
                                        <h2 class="mb-0">
                                            <button class="btn btn-link btn-block text-left session-tab" type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter}}" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
                                            {{ session }}
                                            </button>
                                        </h2>
                                    </div>
                                    <div id="collapse{{ forloop.counter }}" class="collapse {% if forloop.first %}show{% endif %}" aria-labelledby="heading{{ forloop.counter}}" data-parent="#session-payments">
                                        <div class="card-body">
                                            {% if val.enrollments %}
                                                <h4 class="font-weight-bold">Paid Enrollments<span class="float-right">{{ val.paid }}%</span></h4>
                                                <div class="progress mb-5">
                                                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ val.paid }}%"
                                                        aria-valuenow="{{ val.paid }}" aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-8 col-6">
                                                        <h5>User</h5>
                                                    </div>
                                                    <div class="col-lg-4 col-6">
                                                        <h5>Paid</h5>
                                                    </div>
                                                </div>
                                                {% for enrollment in val.enrollments %}
                                                    <div class="row pt-3 pb-2 border-top">
                                                        <div class="col-lg-8 col-6">
                                                            <p>{{ enrollment.student }}</p>
                                                        </div>
                                                        <div class="col-lg-4 col-6">
                                                            <form method="POST" action="{% url 'payment_update' enrollment.id %}">
                                                                {% csrf_token %}
                                                                <fieldset>
                                                                    <div class="row">
                                                                        <div class="col-lg-7 col-6">
                                                                            {{ enrollment.payment|crispy }}
                                                                        </div>
                                                                        <div class="col-lg-5 col-6">
                                                                            <button class="btn btn-success" type="submit"><i class="fas fa-save"></i></button>
                                                                        </div>
                                                                    </div>
                                                                </fieldset>
                                                            </form>
                                                        </div> 
                                                    </div>
                                                {% endfor %}
                                            {% else %}
                                                <p>No students have registered for this session yet.</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock dashboard %}

academy/course/templates/course/feedback_confirm_delete.html
{% extends "course/base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'course/css/simple_nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'course/css/sticky_footer.css' %}">
{% endblock styles %}
{% block content %}
    <div class="form-container rounded shadow form-wide account px-5 py-4">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Delete Feedback</legend>
                <h4 class="text-center">{{ feedback.subject }}</h4>
                <p class="mt-5 text-center">Are you sure you want to delete this feedback?</p>
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-danger mr-2" type="submit">Delete</button>
                <a class="btn btn-secondary" href="{% url 'account' %} ">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

academy/course/templates/course/feedback_user.html
{% extends "course/dashboard.html" %}
{% block content %}
    <h2 class="mb-3">Feedback from {{ view.kwargs.username }} ({{ page_obj.paginator.count }} submitted)</h2>
    {% for feedback in feedback_list %}
        <h4>{{ feedback.subject }}</h4>
        {% if feedback.date_updated|date:"Ymd" > feedback.date_created|date:"Ymd" %}
            <p>Updated: {{ feedback.date_updated|date }}</p>
        {% endif %}
        <p>{{ feedback.user }}</p>
        <p>{{ feedback.date_created|date }}</p>
        <a href="{% url 'feedback_detail' feedback.id %}"><p>Read more...</p></a>
    {% endfor %}
    <div class="text-center">
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4 mr-3" href="?page={{ page_obj.previous_page_number }}"">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num == page_obj.number|add:'-3' or  num == page_obj.number|add:'3' %}
                    <span>...</span>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4 ml-3" href="?page={{ page_obj.next_page_number}} ">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}"">Last</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock content %}

academy/course/templates/course/resource_detail.html
{% extends "course/base.html" %}
{% block content %}
    <a class="btn btn-info mt-1 mb-1" href="{% url 'resource' %}">Back</a>
    <h3>{{ resource.name }}</h3>
    <p>{{ resource.content }}</p>
{% endblock content %}